### ISSUE TITLE
您好，网站预览502。准备修复吗

### ISSUE THREAD

**Issue by 791106912** [CS-Tao/GTD-Visualization#28]
**操作系统和Node版本**
- 操作系统：
- Node：

**Bug 描述**
// TODO:

**Comment by CS-Tao** [comment]
您好，因为网站所在的服务器配置较低，这个服务我已经暂停啦。如果有兴趣，您可以通过 docker 在本地部署网站 [https://github.com/CS-Tao/GTD-Docker](https://github.com/CS-Tao/GTD-Docker)
